### ISSUE TITLE
Bug in vcov() when two ADMB models live in the same folder

### ISSUE THREAD

**Issue by koenvanbenthem** [bbolker/R2admb#16]
Dear R2admb team,

recently I have been trying to fit two admb models on a dataset and compare their outputs. I had put both models in the seem directory and noticed that when I accessed their variance covariance matrix, I obtained the exact same variance-covariance matrix two times. This 'problem' seems to be caused by lines 112-127 in read-funs.r. Here, vcov values are loaded in from a file named 'admodel.cov'. This file seems to be independent of the model file (i.e. the fn variable in that function). To me it seems that admodel.cov will be overwritten everytime admb is run in a specific directory and hence its contents reflect the vcov matrix of the last run instead of of the 'fn' model. [a similar problem seems to exist with the hessian].

I now circumvent this problem by running each model in its own directory, but was wondering if a better method exists. Maybe, it might be good to either issue a warning when multiple .tpl .cor or .std files exist in a folder or to somehow make the name of the admodel.cov specific to the model being fitted, so that no confusion can arise as to which model it belongs to.

Best regards,

Koen van Benthem

**Comment by bbolker** [comment]
Good point.  This document

https://www.researchgate.net/publication/282862345_Details_of_AD_Model_Builder's_covariance_calculations

by Cole Monnahan emphasizes this:

> ADMB creates two temporary binary files to store information about the curvature in un-
bounded space: admodel.hes and admodel.cov. Note that these files maintain this name
regardless of the model name, unlike many other important files generated upon execution.
(Also note that they are considered temporary so the “clean directory” command in the
ADMB-IDE (i.e. emacs) will delete them).

This is a hard-coded behaviour of ADMB, it seems, so the right question would be the best way to work around it.

I've committed something along the lines of what you asked for ...

**Comment by koenvanbenthem** [comment]
Thank you for your rapid reply! I was not aware of that document, it looks generally interesting so also thanks for pointing towards that one.

The warning should largely solve this, so that's great! Like I said, the most important thing is that users are notified when problems may arise :).

**Comment by koenvanbenthem** [comment]
Sorry for spamming again - but out of curiosity, would it not be possible to read the admodel.cov file back in at the end of run_admb and then store it again as paste(fn,"cov",sep=".")? Or would that mess up other things?

**Comment by bbolker** [comment]
It should be possible to do something fancy to avoid problems, but for now (since R2admb does now give a warning) I'm going to close this.
