### ISSUE TITLE
Flexibility wrt to non-standard models

### ISSUE THREAD

**Issue by colemonnahan** [bbolker/R2admb#17]
@bbolker I'm using R2admb for some R code that runs the no-U-turn sampler (NUTS) MCMC algorithm in ADMB . Specifically, I've modified the ADMB source to have this algorithm, and have inputs/outputs that closely match the software package Stan (mc-stan.org). By doing this I can tap into their awesome tools like shinystan.

I use your package, `read_admb` specifically, to read in all the MLE output for things like parameter names and estimates, hessian, etc. However, when I try to run it on the catage example provided by ADMB it throws an error because the report file is non-standard ([seen here](https://github.com/admb-project/admb/blob/master/examples/admb/catage/catage.tpl#L154)).

General advice on whether I should be using R2admb for this? Or specific advice for making it stable? The goal is for my code to work for any model, not necessarily those setup and run using R2admb.

**Comment by bbolker** [comment]
Something like this might have come up in the past, but I don't remember (it's been a while).  It would certainly be reasonable to either (1) fail more gracefully if the report file is non-standard (2) allow a switch to ignore the report file. (An interface I've used in lme4 is to add a control switch with options "ignore", "warn", or "error" -- ignore would mean "don't even try to read the report file", the other options are probably obvious.)

**Comment by colemonnahan** [comment]
Either of those would work well for me with a preference for (1), and would appreciate it.  I'm happy to work off a dev branch at the moment -- how long would it take to get such a edit on CRAN?

**Comment by bbolker** [comment]
Last release came out on CRAN December 7, so probably ought to wait a month before pushing again, but don't see any obstacle to a new release at that time.  (I don't think the actual coding will take long, and testing is not too arduous -- there aren't lots of downstream packages.)

**Comment by colemonnahan** [comment]
Sounds good. It seems as simple as switching stops to warnings but I haven't looked at the code at any depth. Thanks for accomodating.

**Comment by bbolker** [comment]
I think this is fixed and documented now.  Could you check?

Also, I wouldn't mind a more general check if the latest version works more generally for you.  I changed a place where I use `attach()` and am afraid my test coverage isn't that great ...

**Comment by colemonnahan** [comment]
It works for the code I have now: throws a warning and moves on without raising any issues later on.

Admittedly I'm using `read_admb` for pretty simple things, and don't have any thorough tests I can run for you. However,  I will be adding on to this functionality over the next few months and may run in to other issues with `R2admb`. If that's the case I'll let you know. Happy to test where feasible.

Thanks for the quick fix.

**Comment by bbolker** [comment]
Did you encounter any more problems? If not I'm going to close (can always be reopened)

**Comment by colemonnahan** [comment]
Nope, working smoothly so far. I don't foresee any other issues.
