### ISSUE TITLE
glmmADMB "Bounds Error"

### ISSUE THREAD

**Issue by kttempgit** [bbolker/R2admb#18]
I'm currently using mixed-effects zero-inflated negative binomial models from the glmmADMB package. I recently received this error that I am unsure how to resolve:

    formula2 <- as.formula(both[,i] ~ any.virus)
    result.zinb <- glmmadmb(formula2, random=~1|both[,ind_id], data = both, link="log", family="nbinom", zeroInflation=TRUE, verbose=TRUE, debug=TRUE)

    Bounds error in I for i = 127
     I(127) =  0
    u.indexmin() = 1
    u.indexmax() = 59

One thing I do notice is that u.indexmax is the number of individuals in ind_id. I've seen this error written into the code here: http://lists.admb-project.org/pipermail/users/2012-August/001934.html, but I'm not sure how to take that information and resolve the error. Is my data simply too dispersed to converge?

**Comment by bbolker** [comment]
Sorry I didn't see this before. glmmADMB is in a separate github repo, so it would probably be best to post it there: https://github.com/bbolker/glmmadmb/issues . A reproducible example would be nice. I don't know, but I'm guessing that the problem has to do with using matrix indexing in the formula ...

**Comment by bbolker** [comment]
Copied to https://github.com/bbolker/glmmadmb/issues/7
