### ISSUE TITLE
Function to write psv file?

### ISSUE THREAD

**Issue by colemonnahan** [bbolker/R2admb#19]
R2admb has a function to read in a psv file. I'd like to do the opposite: use R to write to a .psv file. The context here is running multiple MCMC chains, reading the separate .psv files in, rbinding them together, write back to disk, and then rerun the ADMB model with `-mceval`.  

This is much simpler than running `-mceval` in each chain and then trying to combine files after, mostly b/c some users have specialized code that executes in the `-mceval` phase.

Is this functionality built into R2admb?

**Comment by bbolker** [comment]
Nope.  Pull requests gladly accepted, knock yourself out :-)

**Comment by colemonnahan** [comment]
OK. I'll write it up locally and then do a pull request once I'm closer on my package. Do you want me to put it into `write_funs.R`?

**Comment by bbolker** [comment]
Sounds fine.

**Comment by bbolker** [comment]
@colemonnahan , did you ever do this? (Not important, just trying to close issues where possible ...)

**Comment by colemonnahan** [comment]
@bbolker I wrote this function into my package here: https://github.com/colemonnahan/adnuts/blob/dev/R/helper.R#L146

Turns out I don't think my package will depend on R2admb, so I now think it makes more sense to just keep it in mine. So I recommend closing this and not taking the action. But if you would find the function useful then that's fine too and I can do a pull request.
